---
title: "DataWrangling"
author: "gzy"
date: "2024-04-18"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(sf)
library(knitr)
library(dplyr)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot) 
library(corrr)   
library(kableExtra)
library(jtools)    
library(ggstance) 
library(ggpubr)
library(broom.mixed) 
library(RColorBrewer)


knitr::opts_chunk$set(echo = TRUE)
```

get the crime data (2022-now)
https://opendataphilly.org/datasets/crime-incidents/


```{r read data}

crime <- st_read("C:/Users/25077/Desktop/crime_data/crime.shp") %>%
  st_transform(crs = st_crs(2272), check = TRUE)

```


```{r crime type preview}

crime.sf %>%
  group_by(text_general_code) %>%
  summarize(count = n()) %>%
  slice_max(order_by = count, n = 10) %>% # This replaces top_n()
  ungroup() %>%
  kable() %>%
  kable_styling()

```
https://cortezdefense.com/federal-classification-of-crimes/#:~:text=Federal%20crimes%20are%20classified%20by,carries%20the%20most%20severe%20punishment.

based on the federal classification of the crime to aggregate the data to varies types and assign corresponding values to each crime.

```{r crime type weighted}


crime.sf <- crime.sf %>%
  mutate(federal_category = case_when(
    text_general_code %in% c("Thefts", "Theft from Vehicle", "Motor Vehicle Theft") ~ "Grade E Felony",
    text_general_code %in% c("Other Assaults") ~ "Class A Misdemeanor",
    text_general_code %in% c("Vandalism/Criminal Mischief") ~ "Class B Misdemeanor",
    text_general_code %in% c("Fraud") ~ "Grade D Felony",
    text_general_code %in% c("Aggravated Assault No Firearm") ~ "Grade C Felony",
    text_general_code %in% c("Aggravated Assault Firearm") ~ "Grade B Felony",
    text_general_code %in% c("Burglary Residential") ~ "Grade D Felony",
    text_general_code %in% c("Homicide - Criminal") ~ "Grade A Felony",
    TRUE ~ "Unclassified"  
  ))

crime.sf.weighted <- crime.sf %>%
  mutate(crime_severity = case_when(
    federal_category == "Grade A Felony" ~ 7,
    federal_category == "Grade B Felony" ~ 6,
    federal_category == "Grade C Felony" ~ 5,
    federal_category == "Grade D Felony" ~ 4,
    federal_category == "Grade E Felony" ~ 3,
    federal_category == "Class A Misdemeanor" ~ 2,
    federal_category == "Class B Misdemeanor" ~ 1.5,
    federal_category == "Class C Misdemeanor" ~ 1,
    federal_category == "Infraction" ~ 0.5,
    federal_category == "Unclassified" ~ 0.5,
    TRUE ~ NA_real_
  ))

```

```{r}
ggplot() +
  geom_sf(data = crime.sf.weighted, aes(colour = crime_severity), 
          show.legend = "point", size = .25) +
  labs(title="crime severity, Philadelphia") +
  theme_void()
```

